sudo: required
dist: trusty

language: cpp

compiler:
  - clang

addons:
    apt:
        sources:
            - llvm-toolchain-trusty-4.0
            - ubuntu-toolchain-r-test
        packages:
            - clang-4.0

install:
  # clang 4.0
  if [ "$CXX" == "clang++" ]; then export CXX="clang++-4.0"; fi
  - |
      if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
        CMAKE_URL="http://www.cmake.org/files/v3.9/cmake-3.9.0.tar.gz"
        mkdir -p ${DEPS_DIR}/cmake
        travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      fi

script: 
    - mkdir build
    - cd build
    - cmake ..
    - make